version: '3.3'
services:
  fake-ledger:
    container_name: fake-ledger
    build: ./fake-ledger
    depends_on:
    - axonserver-1
    - kafka
    ports:
    - "8080:8080"
    entrypoint: /bin/sh
    command: >
      -c "
      while ! (nc -z kafka 9092 ); do sleep 5; echo 'Waiting for kafka to start-up...'; done;
      java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n -jar /app.jar
      "
  fake-payments:
    container_name: fake-payments
    build: ./fake-payments
    depends_on:
    - axonserver-1
    - kafka
    ports:
    - "8083:8080"
    entrypoint: /bin/sh
    command: >
      -c "
      while ! (nc -z kafka 9092 ); do sleep 5; echo 'Waiting for kafka to start-up...'; done;
      java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8787,suspend=n -jar /app.jar
      "
  axonserver-1:
    image: axoniq/axonserver-enterprise:4.5.9-dev
    hostname: axonserver-1
    ports:
    - "8024:8024"
    - "8124:8124"
    - "8224:8224"
    secrets:
    - source: axoniq-license
      target: /axonserver/config/axoniq.license
    - source: axonserver-properties
      target: /axonserver/config/axonserver.properties
    - source: axonserver-token
      target: /axonserver/config/axonserver.token
    environment:
    - AXONIQ_LICENSE=/axonserver/config/axoniq.license
    networks:
    - axon
  axonserver-2:
    image: axoniq/axonserver-enterprise:4.5.9-dev
    hostname: axonserver-2
    ports:
    - "8025:8024"
    - "8125:8124"
    - "8225:8224"
    secrets:
    - source: axoniq-license
      target: /axonserver/config/axoniq.license
    - source: axonserver-properties
      target: /axonserver/config/axonserver.properties
    - source: axonserver-token
      target: /axonserver/config/axonserver.token
    environment:
    - AXONIQ_LICENSE=/axonserver/config/axoniq.license
    networks:
    - axon
  axonserver-3:
    image: axoniq/axonserver-enterprise:4.5.9-dev
    hostname: axonserver-3
    ports:
    - "8026:8024"
    - "8126:8124"
    - "8226:8224"
    secrets:
    - source: axoniq-license
      target: /axonserver/config/axoniq.license
    - source: axonserver-properties
      target: /axonserver/config/axonserver.properties
    - source: axonserver-token
      target: /axonserver/config/axonserver.token
    environment:
    - AXONIQ_LICENSE=/axonserver/config/axoniq.license
    networks:
    - axon
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
    - "2181:2181"
    env_file:
    - config/zookeeper.env
    healthcheck:
      test: /bin/sh -c '[ \"imok\" = \"$$(echo ruok | nc -w 1 127.0.0.1 2181)\" ]' || exit 1
      interval: 1m
  kafka:
    image: confluentinc/cp-kafka:5.0.0
    hostname: kafka
    container_name: kafka
    stop_grace_period: 5m
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    - "29092:29092"
    env_file:
    - config/kafka.env
  schema-registry:
    image: confluentinc/cp-schema-registry:5.0.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
    - zookeeper
    - kafka
    ports:
    - "8081:8081"
    env_file:
    - config/schema-registry.env
secrets:
  axonserver-properties:
    file: ./config/axonserver.properties
  axoniq-license:
    file: ./config/axoniq.license
  axonserver-token:
    file: ./config/axonserver.token
networks:
  axon:
